## Add your printers below

Infinite Benchy Theorem:
  title: "Infinite Benchy Theorem"
  description: "A belted, enclosed 3D printer designed for 24/7 3D printing"
  repository: "https://raw.githubusercontent.com/qcoral/infinite-benchy-theorem/refs/heads/main/journal.md"
  file_name: infinite_benchy_theorem.md

Radeon:
  title: "Radeon"
  description: "A budget-friendly printer designed around CoreXY kinematics and linear rails."
  repository: "https://raw.githubusercontent.com/pmnlla/radeon/refs/heads/master/docs-head.md"
  file_name: pmnlla-radeon.md

3dSpire:
  title: "3d Spire"
  description: "A Core XY printer with linear rails"
  repository: "https://raw.githubusercontent.com/JeffreyWangDev/3dspire/refs/heads/main/design.md"
  file_name: spire.md
  
Quantum One:
  title: "Quantum One"
  description: "An affordable prototyping machine that looks good, performs well, is affordable, and you can build yourself"
  repository: "https://raw.githubusercontent.com/Echo-Labs-Development/Quantum-One/main/plan.md"
  file_name: quantum-one.md

EOS 3D:
  title: "EOS 3D"
  description: "A cheap cantilever 3D printer with full self calibration capabilities."
  repository: "https://raw.githubusercontent.com/AdamTuraj/EOS-3D/refs/heads/main/JOURNAL.md"
  file_name: eos3d.md

Meteroid:
  title: "Meteoroid"
  description: "Production-ready 3d printer based on a Ender 5 frame, with multifunction tool changing. "
  repository: "https://raw.githubusercontent.com/techy-robot/Meteoroid/refs/heads/main/Changelog.md"
  file_name: Meteoroid.md

Mu Draconis:
  title: "Mu Draconis"
  description: "A polar 3d printer with modern hardware, but still not the most practical"
  repository: "https://raw.githubusercontent.com/WilliamPrime/Mu-Draconis/refs/heads/main/design.md"
  file_name: mu-draconis.md

Prism:
  title: "Pr!sm"
  description: "A cheap small 3d printer, a1 mini-like but open source."
  repository: "https://raw.githubusercontent.com/Spectralo/prism/refs/heads/main/README.md"
  file_name: pr!sm.md

Aniprinter:
  title: "Aniprinter"
  description: "A cute anime 3d printer UwU."
  repository: "https://raw.githubusercontent.com/cheyao/aniprinter/refs/heads/main/JOURNAL.md"
  file_name: aniprinter.md

Anixus Vex:
  title: "Anixus Vex"
  description: "A powerful, fast, precise CoreXY 3D printer aimed at intense speed"
  repository: "https://raw.githubusercontent.com/invictus-anic3tus/anixus-vex/refs/heads/main/journal.md"
  file_name: anixus_vex.md

Grasshopper:
  title: "Grasshopper"
  description: "A cheap, fast, CoreXY 3D printer with multicolor capabilities."
  repository: "https://raw.githubusercontent.com/IM-THE-GRASS/Grasshopper/refs/heads/main/journal.md"
  file_name: Grasshopper.md

Sculptura:
  title: "Sculptura"
  description: "Open-source and customized budget 3d printer built from scratch for printing multicolor decorative items :D"
  repository: "https://raw.githubusercontent.com/arsoninstigator/sculptura/refs/heads/main/README.md"
  file_name: sculptura.md

Tesseract:
  title: "Tesseract"
  description: "Affordable 4 axis 3d printer for under 300 dollars"
  repository: "https://raw.githubusercontent.com/EmperorNumerius/Tesseract/refs/heads/main/design.md"
  file_name: tesseract.md

prntr:
  title: "prntr"
  description: "A small, fast printer used for rapid prototyping"
  repository: "https://raw.githubusercontent.com/M0HID/prntr/refs/heads/main/design.md"
  file_name: prntr.md
  
pixl:
  title: "pixl"
  description: "A small corexy printer with a 180 mm cubed build volume"
  repository: "https://raw.githubusercontent.com/vibsthebot/pixl/refs/heads/main/design.md"
  file_name: pixl.md

Veloce:
  title: "Veloce"
  description: "A powerful, fast, precise CoreXY 3D printer, to get more reliable printing"
  repository: "https://raw.githubusercontent.com/RR-CREATOR/Veloce/refs/heads/main/DESIGN.md"
  file_name: veloce.md

B0lta:
  title: "B0lta"
  description: "A fast, precise 3d printer with a large bed, aimed at size over speed"
  repository: "https://raw.githubusercontent.com/AverseABFun/B0lta-printer/refs/heads/main/LAUNCHPAD_SITE.md"
  file_name: b0lta.md

Nighthawk:
  title: "Nighthawk"
  description: "A budget friendly, accurate and enclosed Core-XY printer with a large bed"
  repository: "https://raw.githubusercontent.com/yashsethu/nighthawk/refs/heads/main/logbook.md"
  file_name: nighthawk.md

Comet-eer:
  title: "Comet-eer"
  description: "A 3d printer that is easy to assemble, disassemble and store"
  repository: "https://raw.githubusercontent.com/Froppii/comet-eer/refs/heads/main/LOGS.md"
  file_name: comet-eer.md

Axilab:
  title: "Axilab"
  description: "A fast, cheap and elegant 3d printer with a modern design"
  repository: "https://raw.githubusercontent.com/Rayanlupo/Axilab/refs/heads/main/progresses.md"
  file_name: axilab.md

Volt-core:
  title: "VoltCore"
  description: "Battery-powered 3d printer to print without access to any nearby outlets!"
  repository: "https://raw.githubusercontent.com/TheRealMopcornPuncher/VoltCore/refs/heads/main/CAPTAINSLOG.md"
  file_name: volt-core.md

Infinixar:
  title: "Infinixar"
  description: "CoreXY printer, with extending y axis dimensions"
  repository: "https://raw.githubusercontent.com/GaoYeGithub/Infinixar/refs/heads/main/README.md"
  file_name: infinxar.md

Open Threads:
  title: "Open Threads"
  description: "An attempt at making a sub $200 3D printer from scratch out of mostly printed parts"
  repository: "https://raw.githubusercontent.com/evan-gan/3D-printer/refs/heads/main/journal.md"
  file_name: open-threads.md

Candy-V1:
  title: "Candy-V1"
  description: "A 4-axis 3D printer"
  repository: "https://raw.githubusercontent.com/Outdatedcandy92/CandyV1/refs/heads/main/candy_v1.md"
  file_name: candy_v1.md 

Arcadius:
  title: "Arcadius"
  description: "Arcade Claw Machine-style printer"
  repository: "https://raw.githubusercontent.com/PonderSlime/Arcadius---3D-Printer/refs/heads/main/design.md"
  file_name: Arcadius.md

Reppa:
  title: "Reppa"
  description: "A coreXY printer with klipper"
  repository: "https://raw.githubusercontent.com/KOEGlike/reppa/refs/heads/main/LOG.md"
  file_name: reppa-log.md

X3:
  title: "X3"
  description: "A cheap CoreXY printer that can be made with a Bambu Lab A1 Mini"
  repository: "https://raw.githubusercontent.com/3XAY/X3-3DP/refs/heads/main/JOURNAL.md"
  file_name: x3.md
  
Xyron:
  title: "Xyron"
  description: "A really simple and basic cheap CoreXY printer"
  repository: "https://raw.githubusercontent.com/Rikhav21/Xyron/refs/heads/main/design.md"
  file_name: xyron.md
  
2XInfiniti:
  title: "2xInfiniti"
  description: "A simple 3d printer that uses a conveyor belt and dual extrusion"
  repository: "https://raw.githubusercontent.com/Shadow8928/2XInfiniti/refs/heads/main/README.md"
  file_name: 2XInfinity.md

GreenSpool:
  title: "GreenSpool"
  description: "A green 3D printer that can use plastic as filament"
  repository: "https://raw.githubusercontent.com/dave9123/GreenSpool/refs/heads/main/JOURNAL.md"
  file_name: GreenSpool.md

ChaosCompiler:
  title: "Chaos complied"
  description: "A 3d printer"
  repository: "https://raw.githubusercontent.com/souptik-samanta/ChaosCompiler/refs/heads/main/notes.md"
  file_name: chaos_compiler.md

erLay:
  title: "erLay"
  description: "A ultra portable 3D printer designed for competitions"
  repository: "https://raw.githubusercontent.com/Badbird5907/erLay/refs/heads/master/README.md"
  file_name: erLay.md

Prometheus:
  title: "Prometheus"
  description: "A desktop CoreXY prototyping printer"
  repository: "https://raw.githubusercontent.com/quexeky/prometheus/refs/heads/main/LOGBOOK.md"
  file_name: Prometheus.md

Ducc it:
  title: "Ducc it"
  description: "Can't afford a printer? Ducc it, build one. Cheap CoreXY printer!"
  repository: "https://raw.githubusercontent.com/Dongathan-Jong/Ducc-it/refs/heads/main/Duccbook.md"
  file_name: Ducc-it.md

Padimo Mini:
  title: "Padimo Mini"
  description: "tiny coreXY printer for on the go"
  repositiory: "https://raw.githubusercontent.com/Omegon0/padimo-mini/refs/heads/main/journal.md"
  file_name: padimo-mini.md

Penguin:
  title: "Penguin"
  description: "(Hopefully) The most accurate 3d printer you'll find for under $300."
  repository: "https://raw.githubusercontent.com/Lucas4680/Penguin/refs/heads/main/Devlog.md"
  file_name: Penguin.md

Printopus:
  title: "Printopus"
  description: "A Cheap Printer Which has many cool features such as a built-in how much filament left sensor, custom lighting in the extruder itself, and Video games in the screen itself!"
  repository: "https://raw.githubusercontent.com/scattercat-123/Printopus/refs/heads/main/Printopus-Journey.md"
  file_name: Printopus-Journey.md

Emancipator:
  title: "Emancipator"
  description: "A printer with the ability to automatically eject prints and start a new one."
  repository: "https://raw.githubusercontent.com/Kaympe20/Emancipator/refs/heads/main/JOURNAL.md"
  file_name: emancipator.md

Hephaestus:
  title: "Hephaestus-1"
  description: "A simple CoreXY Printer"
  repository: "https://raw.githubusercontent.com/BoaN235/hephaestus-3D-printer/refs/heads/main/LOG.md"
  file_name: "Hephaestus-1.md"

ED3D:
  title: "ED3D"
  description: "A printer that has hologram showing whats being printed"
  repository: "https://raw.githubusercontent.com/Fastestkyo/ED3D/refs/heads/main/journal.md"
  file_name: ED3D.md

Oblivion:
  title: "Oblivion"
  description: "A1 Mini clone but with enclosure, and maybe linear rails? and try a DIY MMU too"
  repository: "https://raw.githubusercontent.com/hridaya423/oblivion/refs/heads/master/JOURNAL.md"
  file_name: Oblivion.md

Nu:
  title: "Nu"
  description: "A polar, 5 axis 3d printer"
  repository: "https://raw.githubusercontent.com/Magicninja7/Nu/refs/heads/main/LOG.md"
  file_name: Nu.md

Low Powered 3d printer with a display to show progress:
  title: "Solar-Display Printer"
  description: "3d Printer that I hope to integrate with my voice assistant give important stats on a screen on the printer, and make it slightly or completely solar powered "
  repository: "https://raw.githubusercontent.com/broiisapro/Infill-3d-Printer/refs/heads/main/JOURNAL.md"
  file_name: Solar-Display.md

t33ny:
  title: "t33ny"
  description: "A teeny-tiny 3D printer"
  repository: "https://raw.githubusercontent.com/rockwillck/t33ny/refs/heads/main/JOURNAL.md"
  file_name: t33ny.md

FoldPrinter:
  title: "FoldPrinter"
  description: "A very portable 3D printer that will (hopefully) fit inside a briefcase!"
  repository: "https://raw.githubusercontent.com/BingleyPro/foldprinter/refs/heads/main/JOURNAL.md"
  file_name: foldprinter.md

AKPrinter:
  title: "AKPrinter (such a cringe name sob)"
  description: "Prototype CoreXY printer that can self replicate (?) and will be USB-C powered (??)"
  repository: "https://raw.githubusercontent.com/hash-ak/AK-Printer/refs/heads/main/JOURNAL.md"
  file_name: AKPrinter.md

Daedelus:
  title: "Daedelus"
  description: "CoreXY with swapable toolhead"
  repository: "https://raw.githubusercontent.com/meowkewok/Daedelus/refs/heads/main/JOURNAL.md"
  file_name: daedelus.md

ML128E:
  title: "ML128E"
  description: "A compact portable 3d printer with four independent extruders"
  repository: "https://raw.githubusercontent.com/MagmaSpeedCubes/infill/refs/heads/main/JOURNAL.md"
  file_name: ML128E.md

CageHome3D:
  title: "CageHome3D"
  description: "A 3D printer that folds flush to enable efficient storage"
  repository: "https://raw.githubusercontent.com/chunyinkwong/infill-journal/refs/heads/main/README.md"
  file_name: CageHome3D.md
